import type { LevelDef } from '../core/types.ts';

/**
 * W3 さかなつり — 魚をすべて集めてからゴールへ。
 * まっすぐゴールへ向かうだけでは解けず、寄り道の順番が問題になる。
 */
export const W3: LevelDef[] = [
  {
    id: 'W3-1',
    name: 'さかな ひとつ',
    width: 5,
    height: 5,
    layout: [
      ['NW', 'FIXED:NW', 'FISH:NES', 'FIXED:X', 'HOLE'],
      ['FIXED:EW', 'EW', 'ES', 'NES', 'EW'],
      ['FIXED:X', 'X', 'NSW', 'FIXED:SW', 'EW'],
      ['FIXED:NEW', 'FIXED:NES', 'FIXED:NEW', 'FIXED:GOAL:NESW', 'NW'],
      ['NES', 'FIXED:EW', 'FIXED:SW', 'EW', 'FIXED:NW'],
    ],
    catStart: [2, 2],
    optimalMoves: 3,
    parMoves: 5,
    hint: 'さかなを ぜんぶ とってから おうちへ',
  },
  {
    id: 'W3-2',
    name: 'とおまわり',
    width: 5,
    height: 5,
    layout: [
      ['X', 'FIXED:SW', 'FIXED:NSW', 'NW', 'FIXED:ES'],
      ['FIXED:NEW', 'ESW', 'ES', 'FIXED:GOAL:ESW', 'SW'],
      ['FIXED:ES', 'NES', 'NEW', 'FIXED:NEW', 'FIXED:NES'],
      ['FIXED:EW', 'FISH:EW', 'X', 'X', 'HOLE'],
      ['ESW', 'FIXED:EW', 'NSW', 'FIXED:NSW', 'FIXED:NES'],
    ],
    catStart: [4, 2],
    optimalMoves: 4,
    parMoves: 6,
    hint: 'さかなの ほうが とおい ときも ある',
  },
  {
    id: 'W3-3',
    name: 'ふたつの さかな',
    width: 5,
    height: 5,
    layout: [
      ['FIXED:NES', 'NEW', 'EW', 'FIXED:ES', 'FIXED:X'],
      ['HOLE', 'NES', 'FIXED:ES', 'FIXED:NW', 'FIXED:ESW'],
      ['SW', 'NS', 'NS', 'FIXED:NEW', 'FIXED:NE'],
      ['NE', 'FIXED:NES', 'ESW', 'FIXED:GOAL:SW', 'NES'],
      ['FIXED:NES', 'NEW', 'FIXED:FISH:NW', 'EW', 'SW'],
    ],
    catStart: [0, 2],
    optimalMoves: 4,
    parMoves: 6,
    hint: 'いしの うえの さかなは うごかない',
  },
  {
    id: 'W3-4',
    name: 'よりみち',
    width: 5,
    height: 5,
    layout: [
      ['NEW', 'FIXED:GOAL:NS', 'FIXED:EW', 'FIXED:NE', 'FIXED:X'],
      ['FIXED:NS', 'NES', 'NSW', 'NE', 'SW'],
      ['NEW', 'FIXED:EW', 'SW', 'ESW', 'FIXED:FISH:NSW'],
      ['FIXED:NES', 'SW', 'FISH:NE', 'HOLE', 'FIXED:NW'],
      ['FIXED:NES', 'FIXED:NSW', 'NEW', 'FIXED:NW', 'SW'],
    ],
    catStart: [2, 2],
    optimalMoves: 5,
    parMoves: 7,
    hint: 'どちらの さかなを さきに とる？',
  },
  {
    id: 'W3-5',
    name: 'はこんで つる',
    width: 5,
    height: 5,
    layout: [
      ['FIXED:FISH:NEW', 'NEW', 'NSW', 'X', 'FIXED:NE'],
      ['HOLE', 'X', 'NW', 'NEW', 'FIXED:SW'],
      ['FIXED:ES', 'NE', 'NES', 'FIXED:ESW', 'ESW'],
      ['FIXED:NES', 'FIXED:EW', 'NS', 'FIXED:NSW', 'FIXED:X'],
      ['FISH:NES', 'FIXED:GOAL:NESW', 'NS', 'X', 'FIXED:NS'],
    ],
    catStart: [1, 2],
    optimalMoves: 5,
    parMoves: 7,
    hint: 'はこばれる てが ちかみち に なる',
  },
  {
    id: 'W3-6',
    name: 'おおりょう',
    width: 5,
    height: 5,
    layout: [
      ['FIXED:X', 'FIXED:GOAL:NS', 'FIXED:NSW', 'FIXED:SW', 'FIXED:NSW'],
      ['FIXED:NW', 'FISH:ESW', 'NES', 'ES', 'NEW'],
      ['ESW', 'NES', 'HOLE', 'SW', 'FIXED:NSW'],
      ['ES', 'FIXED:NE', 'FISH:NEW', 'NSW', 'FIXED:FISH:EW'],
      ['NE', 'FIXED:ESW', 'FIXED:NW', 'FIXED:NES', 'ESW'],
    ],
    catStart: [2, 1],
    optimalMoves: 6,
    parMoves: 8,
    hint: 'さかな みっつ。じゅんばんを かんがえて',
  },
];
