import type { LevelDef } from '../core/types.ts';

/**
 * W5 やねのうえ — 総合。固定タイル・魚・動くゴールがすべて出る。
 */
export const W5: LevelDef[] = [
  {
    id: 'W5-1',
    name: 'やねのうえ',
    width: 5,
    height: 5,
    layout: [
      ['NSW', 'ES', 'NE', 'FIXED:EW', 'FIXED:NSW'],
      ['NEW', 'FIXED:NEW', 'SW', 'FIXED:NE', 'NE'],
      ['FIXED:FISH:NE', 'HOLE', 'X', 'EW', 'FIXED:NSW'],
      ['FIXED:NEW', 'NESW', 'ESW', 'GOAL:NESW', 'FISH:SW'],
      ['FIXED:SW', 'FIXED:NSW', 'ES', 'FIXED:NES', 'FIXED:NW'],
    ],
    catStart: [1, 2],
    optimalMoves: 5,
    parMoves: 7,
    hint: 'さかなも おうちも ぜんぶ うごく',
  },
  {
    id: 'W5-2',
    name: 'ゆうやけ',
    width: 5,
    height: 5,
    layout: [
      ['NSW', 'FIXED:NW', 'FIXED:NE', 'FIXED:NS', 'FIXED:EW'],
      ['FIXED:NESW', 'NESW', 'NW', 'FIXED:FISH:NW', 'FIXED:NE'],
      ['HOLE', 'NSW', 'GOAL:NES', 'FIXED:SW', 'NE'],
      ['NSW', 'ESW', 'FIXED:NS', 'NW', 'EW'],
      ['FIXED:EW', 'FIXED:X', 'NES', 'ESW', 'NE'],
    ],
    catStart: [3, 3],
    optimalMoves: 5,
    parMoves: 7,
    hint: 'うごかない さかなは おうちを よぶ',
  },
  {
    id: 'W5-3',
    name: 'ほしぞら',
    width: 5,
    height: 5,
    layout: [
      ['FIXED:ES', 'FIXED:NW', 'EW', 'NES', 'FIXED:NESW'],
      ['X', 'NESW', 'FIXED:NSW', 'NSW', 'FIXED:ES'],
      ['NEW', 'FIXED:X', 'FIXED:EW', 'NS', 'FIXED:EW'],
      ['FIXED:SW', 'GOAL:NS', 'NEW', 'FISH:NW', 'FIXED:NW'],
      ['FIXED:FISH:NES', 'ESW', 'NS', 'HOLE', 'NESW'],
    ],
    catStart: [4, 1],
    optimalMoves: 6,
    parMoves: 8,
    hint: 'さかな ふたつと おうち。ぜんぶ かんがえる',
  },
  {
    id: 'W5-4',
    name: 'かぜのみち',
    width: 5,
    height: 5,
    layout: [
      ['ES', 'FIXED:NW', 'NES', 'FIXED:NEW', 'FIXED:NES'],
      ['FIXED:NSW', 'NESW', 'NESW', 'FIXED:FISH:NESW', 'NESW'],
      ['HOLE', 'NE', 'FIXED:FISH:NE', 'NES', 'ES'],
      ['NS', 'X', 'NSW', 'FIXED:ES', 'FIXED:NES'],
      ['GOAL:NEW', 'FIXED:NSW', 'NW', 'FIXED:SW', 'FIXED:X'],
    ],
    catStart: [1, 2],
    optimalMoves: 6,
    parMoves: 8,
    hint: 'あなを どこへ ながす？',
  },
  {
    id: 'W5-5',
    name: 'とおいひ',
    width: 5,
    height: 5,
    layout: [
      ['EW', 'ESW', 'FIXED:ESW', 'HOLE', 'NW'],
      ['FIXED:ES', 'FIXED:NE', 'FIXED:ES', 'NES', 'FISH:NESW'],
      ['X', 'NW', 'FIXED:NEW', 'GOAL:NES', 'NES'],
      ['FIXED:ESW', 'FIXED:NS', 'FIXED:NS', 'FIXED:NEW', 'SW'],
      ['FIXED:X', 'NSW', 'FIXED:ES', 'NESW', 'FISH:NESW'],
    ],
    catStart: [0, 0],
    optimalMoves: 6,
    parMoves: 8,
    hint: 'おうちを うごかすと さかなにも とどく',
  },
  {
    id: 'W5-6',
    name: 'おかえり',
    width: 5,
    height: 5,
    layout: [
      ['FIXED:X', 'NEW', 'NESW', 'FIXED:FISH:EW', 'FIXED:ESW'],
      ['FIXED:SW', 'GOAL:SW', 'HOLE', 'ES', 'FIXED:ES'],
      ['FIXED:FISH:ES', 'NEW', 'ESW', 'FIXED:NE', 'ES'],
      ['NES', 'FIXED:NSW', 'FISH:NSW', 'FIXED:SW', 'FIXED:NSW'],
      ['FIXED:NSW', 'X', 'NS', 'FIXED:NES', 'ESW'],
    ],
    catStart: [0, 1],
    optimalMoves: 7,
    parMoves: 9,
    hint: 'さいごの ステージ。ぜんぶ つかおう',
  },
];
